class Locators:
    url_login= "https://opensource-demo.orangehrmlive.com/web/index.php/auth/login"
    username_field = "username"
    password_field = "password"
    login_button = "//button[@type='submit']"
    error_message = "//p[contains(@class, 'oxd-alert-content-text')]"
    pim_module = "//span[text()='PIM']/ancestor::a[@href='/web/index.php/pim/viewPimModule']"
    search_box = "/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[1]/div/div[2]/div/div/input"
    search_button = "//button[@type='submit']"
    employee_checkbox = "/html/body/div/div[1]/div[2]/div[2]/div/div[2]/div[3]/div/div[1]/div/div[1]/div/label/span"
    delete_button = "/html/body/div/div[1]/div[2]/div[2]/div/div[2]/div[2]/div/div/button"
    confirm_delete_button = "//button[text()=' Yes, Delete ']"
    add_employee_button = "/html/body/div/div[1]/div[2]/div[2]/div/div[2]/div[1]/button"
    first_name_field = "firstName"
    middle_name_field = "middleName"
    last_name_field = "lastName"
    employee_id_field = "//label[text()='Employee Id']/following::input[1]"
    save_button = "//button[@type='submit']"
    personal_details_header = "//h6[text()='Personal Details']"
    other_id_field = "//label[text()='Other Id']/ancestor::div[1]/following-sibling::div/input"
    license_number_field = "/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[2]/div[1]/div/div[2]/input"
    license_expiry_field = "//label[text()='License Expiry Date']/following::input[1]"
    dob_field = "//label[text()='Date of Birth']/following::input[1]"
    marital_status = "/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[1]/div[2]/div/div[2]/div/div"
    marital_status_option = "//span[text()='Married']"
    gender_male = "/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[2]/div[1]/div"
    gender_female = "/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[2]/div[2]/div"
    nationality = "/html/body/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[1]/div[1]/div"
    nationality_option = "//span[text()='Indian']"
    id_input_box = "/html/body/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[2]/div/div[2]/input"
    edit_button = "/html/body/div/div[1]/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div/div/div[9]/div/button[2]"
    profile_icon = "//p[@class='oxd-userdropdown-name']"
    logout_button = "//a[text()='Logout']"

